version: '2'
services:
  newsfilter:
    build:
      context: .
    environment:
      MONGO_HOST: mongodb://mongo:27017
      FLASK_DEBUG: 1
    volumes:
      - .:/newsfilter
    ports:
      - "5000:5000"
  twitter:
    build:
      context: '../twitter'
    env_file: '../.env'
    volumes:
      - ../twitter:/twitter
  alerts:
    build:
      context: '../alerts-rss'
    environment:
      MONGO_HOST: mongodb://mongo:27017
    volumes:
      - ../alerts-rss:/alerts-rss
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
