version: '2'
services:
  newsfilter:
    build:
      context: .
    environment:
      MONGO_HOST: mongodb://mongo:27017
      FLASK_DEBUG: 1
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
