version: '2'
services:
  newsfilter:
    build:
      context: .
    environment:
      MONGO_HOST: mongodb://mongo:27017
    volumes:
      - .:/newsfilter
    ports:
      - "5000:5000"
  alerts:
    build:
      context: '../alerts-rss'
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
